services:
  api:
    build: ./helpdesk-backend
    ports:
      - "8001:8000"
    volumes:
      - ./helpdesk-backend:/app
    env_file:
      - ./helpdesk-backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: ./helpdesk-backend
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./helpdesk-backend:/app
    env_file:
      - ./helpdesk-backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  beat:
    build: ./helpdesk-backend
    command: celery -A app.tasks beat --loglevel=info
    volumes:
      - ./helpdesk-backend:/app
    env_file:
      - ./helpdesk-backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk_secret
      POSTGRES_DB: helpdesk
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helpdesk -d helpdesk"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build: ./helpdesk-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./helpdesk-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8001/api/v1
    depends_on:
      - api

volumes:
  pgdata:
