"""erp expansion models

Revision ID: 7148e4f09975
Revises: ab4e179ddd91
Create Date: 2026-05-12 22:14:20.382813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7148e4f09975'
down_revision: Union[str, None] = 'ab4e179ddd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.create_table('maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenances_id'), 'maintenances', ['id'], unique=False)
    op.drop_index(op.f('ix_ticket_materials_id'), table_name='ticket_materials')
    op.drop_table('ticket_materials')
    op.add_column('inventory_movements', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('inventory_movements', sa.Column('type', sa.String(length=20), nullable=False))
    op.add_column('inventory_movements', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('inventory_movements', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('inventory_movements', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventory_movements_code'), table_name='inventory_movements')
    op.create_unique_constraint(None, 'inventory_movements', ['code'])
    op.create_foreign_key(None, 'inventory_movements', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_column('inventory_movements', 'movement_type')
    op.drop_column('inventory_movements', 'timestamp')
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('stock_minimo', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('serial_number', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('warranty_template_id', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('specs', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'products', 'providers', ['provider_id'], ['id'])
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'category')
    op.drop_column('products', 'min_stock')
    op.add_column('users', sa.Column('signature_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signature_url')
    op.add_column('products', sa.Column('min_stock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.alter_column('products', 'stock',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('products', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'specs')
    op.drop_column('products', 'warranty_template_id')
    op.drop_column('products', 'purchase_date')
    op.drop_column('products', 'serial_number')
    op.drop_column('products', 'provider_id')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'company_id')
    op.drop_column('products', 'cost')
    op.drop_column('products', 'stock_minimo')
    op.drop_column('products', 'type')
    op.drop_column('products', 'barcode')
    op.add_column('inventory_movements', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('inventory_movements', sa.Column('movement_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_constraint(None, 'inventory_movements', type_='unique')
    op.create_index(op.f('ix_inventory_movements_code'), 'inventory_movements', ['code'], unique=True)
    op.alter_column('inventory_movements', 'reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('inventory_movements', 'quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('inventory_movements', 'created_at')
    op.drop_column('inventory_movements', 'type')
    op.drop_column('inventory_movements', 'warehouse_id')
    op.create_table('ticket_materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('ticket_materials_product_id_fkey')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('ticket_materials_ticket_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_materials_pkey'))
    )
    op.create_index(op.f('ix_ticket_materials_id'), 'ticket_materials', ['id'], unique=False)
    op.drop_index(op.f('ix_maintenances_id'), table_name='maintenances')
    op.drop_table('maintenances')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
