"""extended ticket model

Revision ID: ab4e179ddd91
Revises: e985847d04ca
Create Date: 2026-05-12 21:41:11.156590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab4e179ddd91'
down_revision: Union[str, None] = 'e985847d04ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.add_column('tickets', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('requester_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('requester_name', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('requester_dept', sa.String(length=255), nullable=True))
    op.add_column('tickets', sa.Column('technician_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('photo_before', sa.String(length=500), nullable=True))
    op.add_column('tickets', sa.Column('photo_after', sa.String(length=500), nullable=True))
    op.add_column('tickets', sa.Column('closing_signature', sa.String(length=500), nullable=True))
    op.add_column('tickets', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('maps_url', sa.String(length=500), nullable=True))
    op.alter_column('tickets', 'code',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('tickets', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tickets', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('tickets', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(op.f('tickets_code_key'), 'tickets', type_='unique')
    op.create_index(op.f('ix_tickets_code'), 'tickets', ['code'], unique=True)
    op.drop_constraint(op.f('tickets_assigned_tech_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_created_by_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'products', ['asset_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['requester_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['technician_id'], ['id'])
    op.drop_column('tickets', 'closed_at')
    op.drop_column('tickets', 'ai_classification')
    op.drop_column('tickets', 'created_by_id')
    op.drop_column('tickets', 'assigned_tech_id')
    op.drop_column('tickets', 'category')
    op.drop_column('tickets', 'ai_summary')
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.add_column('tickets', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('assigned_tech_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('ai_classification', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_created_by_id_fkey'), 'tickets', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(op.f('tickets_assigned_tech_id_fkey'), 'tickets', 'users', ['assigned_tech_id'], ['id'])
    op.drop_index(op.f('ix_tickets_code'), table_name='tickets')
    op.create_unique_constraint(op.f('tickets_code_key'), 'tickets', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('tickets', 'priority',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('tickets', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tickets', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('tickets', 'code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('tickets', 'maps_url')
    op.drop_column('tickets', 'lng')
    op.drop_column('tickets', 'lat')
    op.drop_column('tickets', 'closing_signature')
    op.drop_column('tickets', 'photo_after')
    op.drop_column('tickets', 'photo_before')
    op.drop_column('tickets', 'asset_id')
    op.drop_column('tickets', 'technician_id')
    op.drop_column('tickets', 'requester_dept')
    op.drop_column('tickets', 'requester_name')
    op.drop_column('tickets', 'requester_id')
    op.drop_column('tickets', 'category_id')
    op.drop_column('tickets', 'department_id')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
